### ISSUE TITLE
Issues with postresql 15

### ISSUE THREAD

**Issue by tintamarre** [rpeden/prefect-docker-compose#2] opened 2022-12-18 12:35 UTC
Just to mention that I had some issues with your configuration. Specifically, after running the default `docker-compose.yml` with --profile [orion, agent, client] for a few hours, I received DB errors. My problem seems to be linked with this one:
https://github.com/PrefectHQ/prefect/issues/7333#issuecomment-1315891885

I fixed it by returning to SQLite. I don't know if downgrading to postgresql:13 will also solve the issue.

**Comment by tintamarre** [comment] 2023-01-04 15:05
Unfortunately, I did not inspect any logs. What occurred was that the front-end was no longer able to retrieve data from the DB. It was quite random.

**Comment by rpeden** [comment] 2023-01-07 15:13
@tintamarre I'm closing this for now since I haven't been able to reproduce the error with the latest version of Prefect. I will keep testing, though - and I appreciate you taking the time to report the issue.

**Closed by rpeden** 2023-01-07 15:13 UTC
